### PR TITLE
Added option to output "raw" data

### PR DESCRIPTION
**Pull request by yckart**
To get the unencoded object, call `toJSON` with `false` as first argument.
- `$page->toJSON(false)`
- `$pages->toJSON(false)`

### CODE REVIEW

**Comment by Stikki** [comment]
Howdy,

Thanks for your contribution. Could you give me one use case where you would need raw stdClass based data, so i can evaluate if it makes sense.

Kind regards

**Comment by yckart** [comment]
With "delayed output" it's pretty helpful to create a $model and add the raw data from specific pages to it (instead of creating plain arrays for each page, for each page-field).

Here's a pretty simple example, untested ;-):

`home.php`

``` php
$model = new stdClass;
$model->title = $page->title;
$model->posts = $pages->find("template=post")->toJSON(false);

if ($config->ajax) {
  echo json_encode($model);
} else {
  require 'app.inc';
}
```

`app.inc`

``` php
include 'head.inc';
echo "<h1>{ $model->title }</h1>";
// ...
include 'foot.inc';
```

**Comment by Stikki** [comment]
Okey, thanks for your input. Explain me what is wrong with using pure PageArray in this case: $model->posts = $pages->find("template=post");

Cause you could be using: $page->title; instead of $model->title;

I'm just trying to get around if method actually should be able to do this or not, because it's kind of default behavior of whole PW anyways.

It's mostly terminology thing here, as i don't think toJSON() should output anything else than JSON.

So let's play with idea for while, answer to question above and i'll play with it.

Cheers

**Comment by yckart** [comment]
Yap, you are right... However, I had the same idea but stucked, since it is not possible to `json_encode` data containing instances of `PageArray`. Or, isn't it?!

**Comment by Stikki** [comment]
It is possible but since it's not stdClass, encoding will blow at some point, that's the reason i created this module. Whole idea is that you can create collection of data and output em in JSON, no matter how deep data goes. Very same data is available in PHP level in PageArray's, so i'm just trying to get my head around WHY this should be supported, as it's already supported native way in PW.

I will think about it and see if this pull request gets more comments, if it does i will proceed.

Thanks a lot for your input and if you get more brilliant ideas, lemme know.

Cheers

**Comment by Stikki** [comment]
Added one public function to module, which also handles stdClass object, so you can even use module like this: $modules('Pages2JSON')->encode($data);

Which then goes trough modules value formatting / checking process and gives JSON string out even for standard stdClass object.

This pull won't happen so closing it.

**Pull request closed without merging**
